# Generated by Django 4.1.3 on 2022-11-23 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_client_hotel_manager_tours_delete_hotels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='date_of_stay',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Дата заезда'),
        ),
    ]
