# Generated by Django 4.1.3 on 2022-11-23 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_tours_date_of_stay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tours',
            name='date_of_stay',
            field=models.DateField(verbose_name='Дата заезда'),
        ),
    ]
