# Generated by Django 4.1.3 on 2022-11-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_alter_tours_date_of_stay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tours',
            name='price',
            field=models.FloatField(verbose_name='Стоимость тура'),
        ),
    ]
