# Generated by Django 4.1.3 on 2022-11-23 19:02

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_alter_tours_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True, verbose_name='Контактный номер'),
        ),
    ]
