# Generated by Django 4.1.3 on 2022-11-24 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_alter_client_options_alter_manager_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='phone',
        ),
    ]
