# Generated by Django 4.1.3 on 2022-11-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_remove_client_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tours',
            name='date_of_exit',
            field=models.DateField(verbose_name='Дата выезда'),
        ),
        migrations.AlterField(
            model_name='tours',
            name='date_of_stay',
            field=models.DateField(verbose_name='Дата заезда'),
        ),
    ]
