# Generated by Django 4.1.3 on 2022-11-24 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_alter_tours_date_of_exit_alter_tours_date_of_stay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tours',
            name='numbers_day',
        ),
    ]
