# Generated by Django 4.1.3 on 2022-11-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0011_alter_tours_price_tour_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour_order',
            name='price',
            field=models.FloatField(verbose_name='Стоимость тура (Руб)'),
        ),
    ]
