# Generated by Django 4.1.3 on 2022-11-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0013_tour_order_people'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour_order',
            name='price',
        ),
        migrations.AddField(
            model_name='tour_order',
            name='discount',
            field=models.FloatField(default=0, verbose_name='Скидка'),
        ),
    ]
