# Generated by Django 4.1.3 on 2022-12-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0014_remove_tour_order_price_tour_order_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour_order',
            name='discount',
        ),
        migrations.AddField(
            model_name='tour_order',
            name='price',
            field=models.FloatField(default=1, verbose_name='Цена'),
        ),
    ]
