# Generated by Django 4.1.3 on 2022-12-02 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0015_remove_tour_order_discount_tour_order_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour_order',
            old_name='price',
            new_name='price_tmp',
        ),
    ]
