# Generated by Django 4.1.3 on 2022-12-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0016_rename_price_tour_order_price_tmp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour_order',
            name='price_tmp',
            field=models.FloatField(verbose_name='Цена'),
        ),
    ]
