# Generated by Django 4.1.3 on 2022-12-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0017_alter_tour_order_price_tmp'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour_order',
            name='status',
            field=models.CharField(choices=[('Предоплата', 'Предоплата'), ('Кредит', 'Кредит')], default='Действует', max_length=100, verbose_name='Cтатус'),
        ),
    ]
