# Generated by Django 4.1.3 on 2022-12-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0018_tour_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour_order',
            name='status',
            field=models.CharField(choices=[('Отменен', 'Отменен'), ('Действует', 'Действует'), ('Завершен', 'Завершен')], default='Действует', max_length=100, verbose_name='Cтатус'),
        ),
    ]
