# Generated by Django 4.1.3 on 2023-03-10 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0019_alter_tour_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='img',
            field=models.ImageField(null=True, upload_to='article'),
        ),
    ]
