# Generated by Django 4.1.3 on 2023-03-10 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0020_manager_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='img',
        ),
        migrations.AddField(
            model_name='manager',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
