# Generated by Django 4.1.3 on 2023-03-10 21:50

from django.db import migrations, models
import tours.models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0021_remove_manager_img_manager_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='image',
            field=models.ImageField(null=True, upload_to=tours.models.directory_path),
        ),
    ]
