# Generated by Django 4.1.3 on 2023-03-11 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0022_alter_manager_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='night',
            field=models.IntegerField(default=1, verbose_name='Ночи'),
        ),
    ]
