# Generated by Django 4.1.3 on 2022-12-08 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0019_alter_tour_order_status'),
        ('tours_status', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('tour_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='+', serialize=False, to='tours.tour_order')),
                ('price', models.FloatField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Оплата тура',
                'verbose_name_plural': 'Оплаты туров',
            },
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
