# Generated by Django 4.1.3 on 2022-12-08 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours_status', '0002_payment_delete_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='price',
        ),
    ]
