# Generated by Django 4.1.3 on 2022-12-13 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours_status', '0006_statistics_alter_payment_date_alter_sale_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Statistics',
        ),
    ]
