# Generated by Django 4.1.3 on 2022-12-13 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0019_alter_tour_order_status'),
        ('tours_status', '0007_delete_statistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('tours_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tours.tours')),
            ],
            options={
                'verbose_name': 'тура',
                'verbose_name_plural': 'туров',
            },
            bases=('tours.tours',),
        ),
    ]
