# Generated by Django 4.1.3 on 2023-03-10 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0020_manager_img'),
        ('tours_status', '0008_stats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stats',
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистика',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tours.tours',),
        ),
    ]
